### ISSUE TITLE
Breaks Custom Chiseled Bookshelves

### ISSUE THREAD

**Issue by Kadynsr** [Benjamin-Norton/BetterBookshelves#5]
I love the mod so so much! I feel like its basically REQUIRED xD but I am developing a mod that adds Chiseled Bookshelves for each wood type, this mod turns all the textures into the regular ones! Dx is there anything you can do? Or something I can do?

**Comment by Benjamin-Norton** [comment]
Adding compatibilities would have to be done on a case-by-case basis as my mod completely rebuilds the model from the ground up, see [ChiseledBookshelfModel.java](https://github.com/Benjamin-Norton/BetterBookshelves/blob/main/src/client/java/com/bawnorton/betterbookshelves/model/ChiseledBookshelfModel.java)
I can add compatibility with your mod but selecting which side textures to use when building the block model, but I'll need to see your mod's code in order to do that.

**Comment by Kadynsr** [comment]
spruce_chiseled_bookshelf
birch_chiseled_bookshelf
jungle_chiseled_bookshelf
acacia_chiseled_bookshelf
dark_oak_chiseled_bookshelf
mangrove_chiseled_bookshelf
cherry_chiseled_bookshelf
bamboo_chiseled_bookshelf
crimson_chiseled_bookshelf
warped_chiseled_bookshelf
gold_chiseled_bookshelf

the texture path is "wanilla:block/chiseled_bookshelf/acacia/acacia_chiseled_bookshelf_(empty, side, top)"

does that give enough information? let me know!

**Comment by Benjamin-Norton** [comment]
That should be enough, I'm assuming the modid is wanilla too because I'll need that to check if your mod is loaded.

**Comment by Kadynsr** [comment]
Yep! You’re a legend! 🙌🏻

**Comment by Benjamin-Norton** [comment]
Never mind, I overlooked a rather important piece of information, I need to know which block I'm building the model for, ie. the block class. 
It would be best if you finished your mod as a standalone and I can add compatibility after it's released to ensure the compatibility patch actually works.

**Comment by Kadynsr** [comment]
I'm just iterating off the default Chiseled Bookshelf class, if that doesn't work I could make a build of my mod and send it

**Comment by Kadynsr** [comment]
what's your discord and I can send it

**Comment by Benjamin-Norton** [comment]
Bawnorton#0001

**Comment by Benjamin-Norton** [comment]
Mods are compatible now.

<img width="1485" alt="Screenshot 2023-03-18 at 5 26 24 PM (2)" src="https://user-images.githubusercontent.com/18416784/226147112-c6f90dc0-a6d8-4c7e-b740-a657a2b66e53.png">

I can't get the "on" text preview to render correctly as the game doesn't consider your blocks to be chiselled block entities, if you want to fix that you can make a PR.
I currently just force the game to render under the crosshair when your mod is loaded instead of on the block itself if text-preview:on is selected.

**Comment by DadoIrie** [comment]
deleted - sorry about that :)
